services:
  - type: web
    name: whatapp-excel
    runtime: docker
    plan: free
    healthCheckPath: /status
    envVars:
      - key: NVIDIA_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
